apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer-config
  # namespace: default  # (this will be overridden by --namespace=${{ env.BRANCH_NAME }})
data:
  verana.json: |
    {
      "chain_name": "verana",
      "chain_id": "vna-devnet-1",
      "status": "live",
      "api": [
        {"provider": "primenode", "address": "http://node1.devnet.verana.network:1317"}
      ],
      "rpc": [
        {"provider": "primenode", "address": "http://node1.devnet.verana.network:26657"}
      ],
      "sdk_version": "0.50.13",
      "coin_type": "118",
      "min_tx_fee": "8000",
      "assets": [{
        "base": "uvna",
        "symbol": "VNA",
        "exponent": "6",
        "logo": "/logos/verana.svg"
      }],
      "addr_prefix": "verana",
      "theme_color": "#161723",
      "logo": "/logos/verana.svg"
    }