name: Deploy Explorer App

on:
  workflow_dispatch:
    inputs:
      CHAIN_NAME:
        description: 'Chain name'
        required: true
        default: 'verana'
      CHAIN_ID:
        description: 'Chain ID'
        required: true
        default: 'vna-devnet-1'
      RPC_ENDPOINTS:
        description: 'JSON array of RPC endpoints'
        required: true
        default: '[{"provider":"primenode","address":"http://node1.devnet.verana.network:26657"}]'
      API_ENDPOINTS:
        description: 'JSON array of API endpoints'
        required: true
        default: '[{"provider":"primenode","address":"http://node1.devnet.verana.network:1317"}]'
      CLUSTER_NODE:
        description: 'Cluster node name'
        required: true
        default: 'cluster-utc-node-07efe5'

env:
  DH_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  DH_TOKEN: ${{ secrets.DOCKER_HUB_PWD }}
  KUBECONFIG_RAW: ${{ secrets.OVH_KUBECONFIG }}
  IMAGE_NAME: 'explorer-app'
  IMAGE_TAG: 'latest'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Update verana.json with Input Values
        run: |
          echo "Updating verana.json..."
          ./scripts/update-verana-json.sh "${{ github.event.inputs.RPC_ENDPOINTS }}" "${{ github.event.inputs.API_ENDPOINTS }}" "${{ github.event.inputs.CHAIN_NAME }}" "${{ github.event.inputs.CHAIN_ID }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DH_USERNAME }}
          password: ${{ env.DH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DH_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Determine Branch Name
        id: determine-branch
        run: |
          echo "BRANCH_NAME=${{ github.event.inputs.CHAIN_NAME }}" >> $GITHUB_ENV

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.9'

      - name: Set up kubeconfig
        run: |
          echo "${{ env.KUBECONFIG_RAW }}" | base64 --decode > k8s_config
          echo "KUBECONFIG=$PWD/k8s_config" >> $GITHUB_ENV

      - name: Create Namespace
        run: |
          kubectl create namespace ${{ env.BRANCH_NAME }} || true

      - name: Deploy ConfigMap
        run: |
          kubectl create configmap explorer-config \
          --from-file=verana.json=./chains/mainnet/verana.json \
          --namespace="$BRANCH_NAME" \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Explorer App
        run: |
          sed "s|yourdockerhubusername/explorer-app:latest|$DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG|" ./kubernetes/explorer-deployment.yaml \
          | kubectl apply -f - --namespace="$BRANCH_NAME"

      - name: Deploy Explorer LoadBalancer Service (optional)
        run: |
          kubectl apply -f kubernetes/explorer-service.yaml --namespace=${{ env.BRANCH_NAME }}

      - name: Deploy Explorer Ingress
        run: |
          kubectl apply -f kubernetes/explorer-ingress.yaml --namespace=${{ env.BRANCH_NAME }}